AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  Exclude:
    - '.bundle/**/*'

Style/Documentation:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table

Metrics/AbcSize:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
